// <auto-generated />
using APINVIBO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APINVIBO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518152031_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("APINVIBO.Models.Invitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Asistira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadNinos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LlevaAcompanante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreAcompanante")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoInvitado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invitados");
                });
#pragma warning restore 612, 618
        }
    }
}
